### ISSUE TITLE
no resolution settings 

### ISSUE THREAD

**Issue by thysson2701** [zhtengw/unraid-i915-sriov#5]
Hello,
when I access the VM with the remote desktop service or teamviewer the resolution is not changeable , it is supposed to be 640x800 but all windows are shifted and can not be operated . no monitor is detected . I have already plugged in an HDMI dongle on the host , no change.

My hardware:
ASRock B660 Pro RS
2nd Gen Intel® Core™ i5-12400

**Comment by zhtengw** [comment]
The VF can not output signal to monitor because of no display framebuffer. Refer https://github.com/strongtz/i915-sriov-dkms/issues/14 and https://github.com/intel/linux-intel-lts/issues/36.

For remote accessing to the guest Windows desktop, only RDP service support resolution change. You can just enable the built-in RDP service in Windows guest and use RDP client to access it.

For now, i915 SR-IOV driver can do nothing on this issue.

**Comment by thysson2701** [comment]
Thanks for the explanation.

I have now tried it with RDP and it works there.

Thanks for the help .
